---
title: "resolution"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{resolution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(obisindicators)
library(dplyr)
library(dggridR) # remotes::install_github("r-barnes/dggridR")
library(sf)
library(arrow)
```

```{r }
# get OBIS records

# obis_20220404.parquet downloaded from https://obis.org/data/access on 2022-04-26
#   NOTE: .gitignore prevents this large file from being on Github
open_parquet_file <- function(filepath){
  occ_all <- open_dataset(filepath)
  # NOTE: there are lots of other fields in the parquet file.
  #     These could be used in the future.
  occ <- occ_all %>%
    group_by(
      decimalLongitude, decimalLatitude, species, date_year) %>%  # remove duplicate rows
    filter(!is.na(species))  %>%
    summarize(
      records = n(),
      .groups = "drop") %>%
    collect()
  # return occ  #I'm not sure what this line is supposed to be doing
}

#occ <- open_parquet_file(here(occ_all <- open_dataset("~/Github/global-obis-es50/obis_20220404.parquet"))) #also not sure what this one is doing

occ_1960s <- occ %>%
  filter(
    date_year >= 1960,
    date_year <= 1969)

occ_1970s <- occ %>%
  filter(
    date_year >= 1970,
    date_year <= 1979)

occ_1980s <- occ %>%
  filter(
    date_year >= 1980,
    date_year <= 1989)

occ_1990s <- occ %>%
  filter(
    date_year >= 1990,
    date_year <= 1999)

occ_2000s <- occ %>%
  filter(
    date_year >= 2000,
    date_year <= 2009)

occ_2010s <- occ %>%
  filter(
    date_year >= 2010,
    date_year <= 2019) 

occ_2020s <- occ %>%
  filter(
    date_year >= 2020,
    date_year <= 2029) 
    
```

## Create function to make grid, calculate metrics for different resolution grid sizes

```{r function}
res_changes <- function(occur, resolution = 9){
    dggs <- dgconstruct(projection = "ISEA", topology = "HEXAGON", res = resolution)
    occur$cell <- dgGEO_to_SEQNUM(dggs, occur$decimalLongitude, occur$decimalLatitude)[["seqnum"]]
    idx <- calc_indicators(occur)

  grid <- dgcellstogrid(dggs, idx$cell) %>%
    st_wrap_dateline() %>%
    rename(cell = seqnum) %>%
    left_join(
      idx,
      by = "cell")
  return(grid)
}
```

## plot stuff
```{r}
RES <- 6
grid_1960s <- res_changes(occ_1960s, RES)
grid_1970s <- res_changes(occ_1970s, RES)
grid_1980s <- res_changes(occ_1980s, RES)
grid_1990s <- res_changes(occ_1990s, RES)
grid_2000s <- res_changes(occ_2000s, RES)
grid_2010s <- res_changes(occ_2010s, RES)
grid_2020s <- res_changes(occ_2020s, RES)
gmap_indicator(grid_1960s, "es", label = "ES(50)")
gmap_indicator(grid_1970s, "es", label = "ES(50)")
gmap_indicator(grid_1980s, "es", label = "ES(50)")
gmap_indicator(grid_1990s, "es", label = "ES(50)")
gmap_indicator(grid_2000s, "es", label = "ES(50)")
gmap_indicator(grid_2010s, "es", label = "ES(50)")
gmap_indicator(grid_2020s, "es", label = "ES(50)")
```
